from balancesheet_itooza import *

# MakeDataFrameforDisplay(MakeDataStorage('엠씨넥스'))
# MakeDataFrameforDisplay(MakeDataStorage('탑엔지니어링'))
# MakeDataFrameforDisplay(MakeDataStorage('인탑스'))
# MakeDataFrameforDisplay(MakeDataStorage('GST'))
# MakeDataFrameforDisplay(MakeDataStorage('엘비세미콘'))
# MakeDataFrameforDisplay(MakeDataStorage('삼화콘덴서공업'))
# MakeDataFrameforDisplay(MakeDataStorage('제노레이'))
# MakeDataFrameforDisplay(MakeDataStorage('서흥'))
# MakeDataFrameforDisplay(MakeDataStorage('제너셈'))
# MakeDataFrameforDisplay(MakeDataStorage('인텍플러스'))
# MakeDataFrameforDisplay(MakeDataStorage('인피니트헬스케어'))
# MakeDataFrameforDisplay(MakeDataStorage('삼성전기'))
# MakeDataFrameforDisplay(MakeDataStorage('상아프론테크'))
# MakeDataFrameforDisplay(MakeDataStorage('신흥에스이씨'))
# MakeDataFrameforDisplay(MakeDataStorage('씨아이에스'))
# MakeDataFrameforDisplay(MakeDataStorage('이노와이어리스'))
# MakeDataFrameforDisplay(MakeDataStorage('엔에스'))
# MakeDataFrameforDisplay(MakeDataStorage('쎄트렉아이'))
# MakeDataFrameforDisplay(MakeDataStorage('서울반도체'))
# MakeDataFrameforDisplay(MakeDataStorage('테스나'))
# MakeDataFrameforDisplay(MakeDataStorage('칩스앤미디어'))
# MakeDataFrameforDisplay(MakeDataStorage('나무기술'))
MakeDataFrameforDisplay(MakeDataStorage('후성'))
MakeDataFrameforDisplay(MakeDataStorage('LG헬로비전'))

df = pd.DataFrame(DataList)
df.to_html('./financedata/today.html')
writer = pd.ExcelWriter('stock.xlsx', engine='xlsxwriter')
df.to_excel(writer, sheet_name='today')
writer.save()