from balancesheet_itooza import *

MakeDataFrameforDisplay(MakeDataStorage('엠씨넥스'))
MakeDataFrameforDisplay(MakeDataStorage('탑엔지니어링'))
MakeDataFrameforDisplay(MakeDataStorage('바이오로그디바이스'))
MakeDataFrameforDisplay(MakeDataStorage('에코마케팅'))
MakeDataFrameforDisplay(MakeDataStorage('인탑스'))
MakeDataFrameforDisplay(MakeDataStorage('세코닉스'))
MakeDataFrameforDisplay(MakeDataStorage('한국알콜'))
MakeDataFrameforDisplay(MakeDataStorage('GST'))
MakeDataFrameforDisplay(MakeDataStorage('엘비세미콘'))
MakeDataFrameforDisplay(MakeDataStorage('해성옵틱스'))
MakeDataFrameforDisplay(MakeDataStorage('한화솔루션'))
MakeDataFrameforDisplay(MakeDataStorage('오텍'))
MakeDataFrameforDisplay(MakeDataStorage('휴온스'))
MakeDataFrameforDisplay(MakeDataStorage('디에이치피코리아'))
MakeDataFrameforDisplay(MakeDataStorage('이씨에스'))
MakeDataFrameforDisplay(MakeDataStorage('창해에탄올'))
MakeDataFrameforDisplay(MakeDataStorage('한익스프레스'))
MakeDataFrameforDisplay(MakeDataStorage('해마로푸드서비스'))
MakeDataFrameforDisplay(MakeDataStorage('삼화콘덴서'))
MakeDataFrameforDisplay(MakeDataStorage('서흥'))
MakeDataFrameforDisplay(MakeDataStorage('제너셈'))
MakeDataFrameforDisplay(MakeDataStorage('삼지전자'))
MakeDataFrameforDisplay(MakeDataStorage('쿠쿠홈시스'))
MakeDataFrameforDisplay(MakeDataStorage('제이에스코퍼레이션'))
MakeDataFrameforDisplay(MakeDataStorage('인피니트헬스케어'))
MakeDataFrameforDisplay(MakeDataStorage('인텍플러스'))
MakeDataFrameforDisplay(MakeDataStorage('삼성전기'))
MakeDataFrameforDisplay(MakeDataStorage('포시에스'))
MakeDataFrameforDisplay(MakeDataStorage('씨아이에스'))
MakeDataFrameforDisplay(MakeDataStorage('상아프론테크'))
MakeDataFrameforDisplay(MakeDataStorage('이노와이어리스'))
MakeDataFrameforDisplay(MakeDataStorage('알서포트'))
MakeDataFrameforDisplay(MakeDataStorage('엔에스'))
MakeDataFrameforDisplay(MakeDataStorage('네패스'))
MakeDataFrameforDisplay(MakeDataStorage('바디텍메드'))
MakeDataFrameforDisplay(MakeDataStorage('화승엔터프라이즈'))
MakeDataFrameforDisplay(MakeDataStorage('서울반도체'))
MakeDataFrameforDisplay(MakeDataStorage('쎄트렉아이'))
MakeDataFrameforDisplay(MakeDataStorage('이퓨쳐'))
MakeDataFrameforDisplay(MakeDataStorage('한솔시큐어'))
MakeDataFrameforDisplay(MakeDataStorage('테스나'))
MakeDataFrameforDisplay(MakeDataStorage('파마리서치프로덕트'))
MakeDataFrameforDisplay(MakeDataStorage('메가엠디'))
MakeDataFrameforDisplay(MakeDataStorage('한국콜마'))
MakeDataFrameforDisplay(MakeDataStorage('칩스앤미디어'))
MakeDataFrameforDisplay(MakeDataStorage('옴니텔'))
MakeDataFrameforDisplay(MakeDataStorage('인텔리안테크'))
MakeDataFrameforDisplay(MakeDataStorage('나무기술'))
MakeDataFrameforDisplay(MakeDataStorage('디피씨'))
MakeDataFrameforDisplay(MakeDataStorage('후성'))
MakeDataFrameforDisplay(MakeDataStorage('알엔투테크놀로지'))
MakeDataFrameforDisplay(MakeDataStorage('우정바이오'))
MakeDataFrameforDisplay(MakeDataStorage('덕산네오룩스'))
MakeDataFrameforDisplay(MakeDataStorage('삼천당제약'))
MakeDataFrameforDisplay(MakeDataStorage('스튜디오드래곤'))


df = pd.DataFrame(DataList)
df.to_html('./financedata/today.html')
writer = pd.ExcelWriter('today.xlsx', engine='xlsxwriter')
df.to_excel(writer, sheet_name='today')
writer.save()