from balancesheet_itooza import *

MakeDataFrameforDisplay(MakeDataStorage('삼화콘덴서'))
MakeDataFrameforDisplay(MakeDataStorage('서흥'))
MakeDataFrameforDisplay(MakeDataStorage('삼성전기'))
MakeDataFrameforDisplay(MakeDataStorage('디피씨'))
MakeDataFrameforDisplay(MakeDataStorage('삼지전자'))
MakeDataFrameforDisplay(MakeDataStorage('서울반도체'))
MakeDataFrameforDisplay(MakeDataStorage('인탑스'))
MakeDataFrameforDisplay(MakeDataStorage('세코닉스'))
MakeDataFrameforDisplay(MakeDataStorage('엘비세미콘'))
MakeDataFrameforDisplay(MakeDataStorage('인텍플러스'))
MakeDataFrameforDisplay(MakeDataStorage('탑엔지니어링'))
MakeDataFrameforDisplay(MakeDataStorage('인피니트헬스케어'))
MakeDataFrameforDisplay(MakeDataStorage('이노와이어리스'))
MakeDataFrameforDisplay(MakeDataStorage('해성옵틱스'))
MakeDataFrameforDisplay(MakeDataStorage('GST'))
MakeDataFrameforDisplay(MakeDataStorage('상아프론테크'))
MakeDataFrameforDisplay(MakeDataStorage('후성'))
MakeDataFrameforDisplay(MakeDataStorage('칩스앤미디어'))
MakeDataFrameforDisplay(MakeDataStorage('엠씨넥스'))
MakeDataFrameforDisplay(MakeDataStorage('쎄트렉아이'))
MakeDataFrameforDisplay(MakeDataStorage('한국콜마'))
MakeDataFrameforDisplay(MakeDataStorage('인텔리안테크'))
MakeDataFrameforDisplay(MakeDataStorage('제이에스코퍼레이션'))
MakeDataFrameforDisplay(MakeDataStorage('바디텍메드'))
MakeDataFrameforDisplay(MakeDataStorage('해마로푸드서비스'))
MakeDataFrameforDisplay(MakeDataStorage('에코마케팅'))
MakeDataFrameforDisplay(MakeDataStorage('휴온스'))
MakeDataFrameforDisplay(MakeDataStorage('스튜디오드래곤'))
MakeDataFrameforDisplay(MakeDataStorage('쿠쿠홈시스'))

df = pd.DataFrame(DataList)
df.to_html('./financedata/today.html')
writer = pd.ExcelWriter('stock.xlsx', engine='xlsxwriter')
df.to_excel(writer, sheet_name='today')
writer.save()